src/Entity/Circuit.php
<?php

namespace App\Entity;

use App\Repository\CircuitRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CircuitRepository::class)
 */
class Circuit
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $course;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $teacher;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $student;

    /**
     * @ORM\Column(type="integer")
     */
    private $duration;

    /**
     * @ORM\Column(type="integer")
     */
    private $difficulties;

    /**
     * @ORM\Column(type="integer")
     */
    private $success;

    /**
     * @ORM\Column(type="integer")
     */
    private $diplomas;

    /**
     * @ORM\Column(type="string", length=1000)
     */
    private $picture;

    /**
     * @ORM\OneToMany(targetEntity=Teacher::class, mappedBy="circuit")
     */
    private $teachers;

    /**
     * @ORM\OneToMany(targetEntity=Review::class, mappedBy="reviews")
     */
    private $reviews;

    public function __construct()
    {
        $this->teachers = new ArrayCollection();
        $this->reviews = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }
    public function getCourse(): ?string
    {
        return $this->course;
    }

    public function setCourse(string $course): self
    {
        $this->course = $course;

        return $this;
    }
    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDuration(): ?int
    {
        return $this->duration;
    }

    public function setDuration(int $duration): self
    {
        $this->duration = $duration;

        return $this;
    }

    public function getDifficulties(): ?int
    {
        return $this->difficulties;
    }

    public function setDifficulties(int $difficulties): self
    {
        $this->difficulties = $difficulties;

        return $this;
    }

    public function getSuccess(): ?int
    {
        return $this->success;
    }

    public function setSuccess(int $success): self
    {
        $this->success = $success;

        return $this;
    }

    public function getDiplomas(): ?int
    {
        return $this->diplomas;
    }

    public function setDiplomas(int $diplomas): self
    {
        $this->diplomas = $diplomas;

        return $this;
    }
    public function getTeacher(): ?string
    {
        return $this->teacher;
    }

    public function setTeacher(string $teacher): self
    {
        $this->teacher = $teacher;

        return $this;
    }
    public function getStudent(): ?string
    {
        return $this->student;
    }

    public function setStudent(string $student): self
    {
        $this->student = $student;

        return $this;
    }
    
    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    /**
     * @return Collection<int, Teacher>
     */
    public function getTeachers(): Collection
    {
        return $this->teachers;
    }

    public function addTeacher(Teacher $teacher): self
    {
        if (!$this->teachers->contains($teacher)) {
            $this->teachers[] = $teacher;
            $teacher->setCircuit($this);
        }

        return $this;
    }

    public function removeTeacher(Teacher $teacher): self
    {
        if ($this->teachers->removeElement($teacher)) {
            // set the owning side to null (unless already changed)
            if ($teacher->getCircuit() === $this) {
                $teacher->setCircuit(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Review>
     */
    public function getReviews(): Collection
    {
        return $this->reviews;
    }

    public function addReview(Review $review): self
    {
        if (!$this->reviews->contains($review)) {
            $this->reviews[] = $review;
            $review->setReviews($this);
        }

        return $this;
    }

    public function removeReview(Review $review): self
    {
        if ($this->reviews->removeElement($review)) {
            // set the owning side to null (unless already changed)
            if ($review->getReviews() === $this) {
                $review->setReviews(null);
            }
        }

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function DisplayRole() : string
    {
    

        $displayRole = '';
        if (in_array('ROLE_ADMIN', $this->roles)) {
    
            $displayRole = 'Administrateur';
        } elseif(in_array('ROLE_MANAGER', $this->roles)) {
        
            $displayRole = 'Manager';

        } elseif(in_array('ROLE_USER', $this->roles)) {


            $displayRole = 'Utilisateur';
        }
        return $displayRole;


    

    }
}

src/Form/CircuitType.php
<?php

namespace App\Form;

use App\Entity\Circuit;
use App\Entity\Teacher;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;



class CircuitType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('description')
            //->add('course')
            /*->add('teachers',EntityType::class, 
            
            [
               
                'class' => Teacher::class,
                'choice_label' => 'getFirstnameAndLastnameOfTeachers',
                'multiple' => true,
                'expanded' => true,
            ])*/
            //->add('student')
            ->add('duration')
            ->add('difficulties')
            ->add('success')
            ->add('diplomas')
            ->add('picture')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Circuit::class,
        ]);
    }
}

src/Controller/Back/CircuitController.php
<?php

namespace App\Controller\Back;

use App\Entity\Circuit;
use App\Form\CircuitType;
use App\Repository\CircuitRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/back/circuit")
 */
class CircuitController extends AbstractController
{
    /**
     * @Route("/", name="app_back_circuit_index", methods={"GET"})
     */
    public function index(CircuitRepository $circuitRepository): Response
    {
        return $this->render('back/circuit/index.html.twig', [
            'circuits' => $circuitRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_back_circuit_new", methods={"GET", "POST"})
     */
    public function new(Request $request, CircuitRepository $circuitRepository): Response
    {
        $circuit = new Circuit();
        $form = $this->createForm(CircuitType::class, $circuit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $circuitRepository->add($circuit, true);

            return $this->redirectToRoute('app_back_circuit_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('back/circuit/new.html.twig', [
            'circuit' => $circuit,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_back_circuit_show", methods={"GET"})
     */
    public function show(Circuit $circuit): Response
    {
        return $this->render('back/circuit/show.html.twig', [
            'circuit' => $circuit,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_back_circuit_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Circuit $circuit, CircuitRepository $circuitRepository ): Response
    {
        $form = $this->createForm(CircuitType::class, $circuit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $circuitRepository->add($circuit, true);

            $this->addFlash(
                'notice',
                'les modifications ont bien été sauvegardées!'
            );

            return $this->redirectToRoute('app_back_circuit_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('back/circuit/edit.html.twig', [
            'circuit' => $circuit,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_back_circuit_delete", methods={"POST"})
     */
    public function delete(Request $request, Circuit $circuit, CircuitRepository $circuitRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$circuit->getId(), $request->request->get('_token'))) {
            $circuitRepository->remove($circuit, true);
        } else {
            $this->addFlash(
                'error',
                'les modifications n\'ont pas été supprimées!'
            );


        }

        return $this->redirectToRoute('app_back_circuit_index', [], Response::HTTP_SEE_OTHER);
    }
}

src/Controller/CircuitController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\CircuitRepository;
use App\Repository\ReviewRepository;
use App\Entity\Circuit;
use Doctrine\ORM\EntityManagerInterface;

class CircuitController extends AbstractController
{



    /**
     * @Route("/circuit/{id}", name="circuit", requirements={"id": "\d+"})
     */
    public function show(CircuitRepository $circuitRepo, int $id, ReviewRepository $reviewRepo): Response
    {
        $circuit = $circuitRepo->find($id);
        //dump($circuit);
        //dd($circuit);

        $lastReviews = $reviewRepo->findBy(['reviews' => $circuit], ['id' => 'DESC'], 1);

    
        return $this->render('circuit/show.html.twig',
            
            [
                'lastReviews' => $lastReviews,
                'circuit' => $circuit
            ]
        );
    }


    /**
     * @Route("/", name="cursus")
     */
    public function list(circuitRepository $circuitRepository): Response
    {
        $cursus = $circuitRepository->findAll();
   
    
        return $this->render(
            'circuit/home.html.twig',
            [
                "cursus" => $cursus,
            ]
        );
    }



    /**
    * @Route("/cursus/create", name="cursus_create")
    */
    public function create(EntityManagerInterface $doctrine)
    {

        $newCursus = new Circuit();
        $newCursus->setTitle("MBA ping pong");
        $newCursus->setDescription("MBA ping pong");
        $newCursus->setDuration(4);
        $newCursus->setDifficulties(5);
        $newCursus->setSuccess(90);
        $newCursus->setDiplomas(6);
        $newCursus->setPicture('https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzIxGr3fYeh-l173RsqkMkOrClQVDmxYirxA&usqp=CAU');



        //dump($newCursus);

        $doctrine->persist($newCursus);

        $doctrine->flush();

        //dd($newCursus);

        return $this->redirectToRoute("cursus");

    }

    /**
     * @Route("/cursus/update/{id}", requirements={"id": "\d+"})
     */
    public function update($id, CircuitRepository $circuitRep, EntityManagerInterface $doctrine)
    {

        $cursus = $circuitRep->find($id);

        $cursus->setTitle('Ahlam ' . mt_rand(2, 99));


        $doctrine->flush();


        return $this->redirectToRoute("circuit", array("id" => $id));


    }
    

    /**
     * @Route("/cursus/delete/{id}", requirements={"id": "\d+"})
     */
    public function delete($id, CircuitRepository $circuitRep, EntityManagerInterface $doctrine)
    {

        $cursus = $circuitRep->find($id);

        $doctrine->remove($cursus);
    
        $doctrine->flush();


        return $this->redirectToRoute("cursus");


    }


























}

templates/circuit/home.html.twig
{# twig comments syntaxe #}

{% extends 'base.html.twig' %}

{% block title %}
  <div class="col-lg-6 mx-auto text-center ">
         <p class="lead mb-4 text-muted fst-normal fw-bold">cassiopeia</p>
    </div>

{% endblock  %}

{% block body %}
<div class="my-2 py-2 text-center">
    <img src="{{ asset('assets/favicon.png') }}" height="100" alt="logo" class="logo">
    <h1 class="display-6 fw-bold">Enseignements, Exellence, quality </h1>
  
</div>

<div class="my-0 py-0 text-center">
    <div class="col-lg-9 mx-auto">
            <h2 class="display-7 fw-bold">Les cursus</h2>
           
        <div class="row row-cols-1 row-cols-md-2 g-2 ">
            {% for cursus in cursus %}
            <div class="d-inline p-2 ">
                <div class="card h-100 border-dark">

{% if app.session.get('theme') == 'firstTheme' %}
    <div class="card-body"  style="background: linear-gradient(180deg, blue, black)";>
     <h2><a class="link" href="{{ path('circuit', {'id' : cursus.id }) }}"  class="link-underline-light" >{{ cursus.title }}</a></h2><br>
    <h3 class="card-number fst-normal" style="color: #1515ce";>Diplôme Bac + {{ cursus.diplomas }}</h3>
    <h4 class="card-percent fst-normal" style="color: #1515ce">Admission sur concours</h4>


{% else %}
       <div class="card-body text-light"  style="background-color: #000000";>
   <h2><a class="link_theme" href="{{ path('circuit', {'id' : cursus.id }) }}"  style="color= #0d6efd" class="link-underline-light" >{{ cursus.title }}</a></h2><br> 
    <h3 class="card-number fst-normal" style="color: #0d6efd";>Diplôme Bac + {{ cursus.diplomas }}</h3>
  <h5 class="card-percent fst-normal"style="color: #0d6efd">Admission sur concours</h5>


{% endif %}  
                 
                                              
 </div>
</div>
</div>

{% endfor %}

  
<div class="card" style="width: 25%";>
  <img src="https://www.objets-de-legende.fr/wp-content/uploads/sites/222/2017/12/motarboard-histoire.png" class="card-img-top" alt="...">
  <div class="card-body" style="background-color: #000000">
    <h5 class="card-title">Les Lauréas 2022</h5>
    <p class="card-text">La route à été courbe et sinueuse mais ils ont gardés l'esprit droit, they did it, Congratulations</p>
    <a href="{{ path ('laureat') }}" class="btn btn-dark fst-normal" style="background: linear-gradient(250deg, grey, black)">see more</a>
  </div>
</div> 
<div class="card" style="width: 25%;">
  <img src="https://static.wixstatic.com/media/108ff4_8d9dc6bb2d9e4470903c5a303890cfa5~mv2.jpg/v1/fill/w_640,h_496,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/108ff4_8d9dc6bb2d9e4470903c5a303890cfa5~mv2.jpg" class="card-img-top" alt="...">
  <div class="card-body" style="background: linear-gradient(250deg, blue, black)">
    <h5 class="card-title">Cassiopeia Internationale</h5>
    <p class="card-text">Parceque nous sommes ouvert au monde et aux cerveaux , nous sommes présent sur tous les continents</p>
    <a href="#" class="btn btn-dark fst-normal" style="background: linear-gradient(250deg, blue, black)">see more</a>
  </div>

</div>
<div class="card" style="width: 25%;">
  <img src="https://images.rtl.fr/~c/2000v2000/rtl/www/1162944-luca-de-meo-pdg-de-renault.jpg" class="card-img-top" alt="...">
  <div class="card-body" style="background-color: #000000">
    <h5 class="card-title ">Les anciens</h5>
    <p class="card-text ">Ils sont liés à Cassipoeia, aujourd'hui ils sont directeur financier , économiste et plus encore</p>
    <a href="#" class="btn btn-dark fst-normal" style="background: linear-gradient(250deg, grey, black)">see more</a>
  </div>
</div>
<div class="card" style="width: 25%;">
  <img src="https://assets.website-files.com/606053c53975b03fbab75e38/61ea75414264666bbe1587ac_14.jpg" class="card-img-top" alt="...">
  <div class="card-body" style="background: linear-gradient(250deg, blue, black)">
    <h5 class="card-title">Nos objectifs</h5>
    <p class="card-text ">Toujours plus, encore mieux notre fil conducteur , mieux qu'hier, moins bien que demain</p>
    <a href="#" class="btn btn-dark fst-normal text-primary" style="background: linear-gradient(250deg, blue, black)" >see more</a>
  </div>
  </div>

</div>


</div>
{% endblock  %}

templates/circuit/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello CircuitController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ '/var/www/html/cassiopeia/src/Controller/CircuitController.php'|file_link(0) }}">src/Controller/CircuitController.php</a></code></li>
        <li>Your template at <code><a href="{{ '/var/www/html/cassiopeia/templates/circuit/index.html.twig'|file_link(0) }}">templates/circuit/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/circuit/show.html.twig
{% extends 'base.html.twig' %}



{% block title %}
<div class="col-lg-6 mx-auto text-center ">
     <p class="lead mb-4 text-muted fst-normal fw-bold">cassiopeia</p>
</div>
<div class="my-2 py-2 text-center">    
    <img src="{{ asset('assets/favicon.png') }}" height="100" alt="logo" class="logo">
    <h1 class="display-6 fw-bold">Enseignements, Exellence, quality </h1>
  
</div>

{% endblock %}

{% block body %}



<div class=" text-center">
    <div class="mx-auto">
        
            <h2 class="card-title fst-normal fw-bolder">{{ circuit.title }}</h2>
        <div class= "container mt-2">
          
            <div class="d-inline p-2">
                <div class="card border-dark">


{% if app.session.get('theme') == 'firstTheme' %}

        <div class="card-body text-primary" style="background: linear-gradient(180deg, blue, black)">

{% else %}             

    <div class="card-body  text-primary" style="background-color: #000000">

{% endif %}  
        <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm bg-with">
        <img class="col-4 movie__poster img-thumbnail" style="background-image: url({{ circuit.picture }});" class="images">
                
            
        <h3 class="card-percent fst-normal">{{ circuit.description }}</h4>
        <p class="card-text fst-normal">{{ circuit.duration }} ans de formation</p>
        <h3 class="card-number fst-normal">diplôme Bac + {{ circuit.diplomas }}</h3>
        <h4 class="card-percent fst-normal">taux de réussite {{ circuit.success }} %</h4>
        <h5 class="card-percent fst-normal">difficulté => {{ circuit.difficulties }}</h5><br><br>

        <ul class="list-group">
        <li class="list-group-item">enseigné par Mr et Mme</li>

{% for teacher in circuit.teachers %}
       
                  <li class="list-group-item">{{ teacher.firstname }} {{ teacher.lastname }}</li>
                </ul>
{% endfor %}


        <a class="fst-normal" href="{{ path('circuit_review_add', {id: circuit.id}) }}">ajouter un commentaire</a>
            
           <ul class="list-group-review">


        <li class="list-group-review">Le dernier commentaire</li>
        {% for lastReview in lastReviews %}
                  <li class="list-group-review">{{ lastReview.username }}<br>{{ lastReview.title }}<br>{{ lastReview.description }}<br>{{ lastReview.rating }}<br>  </li>
        {% else %}
           <h4 class="card-percent fst-normal">Pas de commentaire pour le moment</h4>

        {% endfor %}
                </ul>

          </div>
  </div>
 </div>
         </div>
            
         </div>
               
        </div>
    </div>
</div>









{% endblock %}